"""Mapping from stock ticker symbols to canonical company display names."""

TICKER_NAMES: dict[str, str] = {
    "ADBE": "Adobe",
    "AI": "C3.ai",
    "AMZN": "Amazon",
    "APPF": "AppFolio",
    "ASAN": "Asana",
    "CFLT": "Confluent",
    "CRM": "Salesforce",
    "CRWD": "CrowdStrike",
    "CXM": "Sprinklr",
    "DDOG": "Datadog",
    "DOCN": "DigitalOcean",
    "DOCU": "DocuSign",
    "DT": "Dynatrace",
    "FRSH": "Freshworks",
    "GOOGL": "Alphabet (Google)",
    "GTLB": "GitLab",
    "HUBS": "HubSpot",
    "IOT": "Samsara",
    "KVYO": "Klaviyo",
    "MDB": "MongoDB",
    "META": "Meta",
    "MNDY": "Monday.com",
    "MSFT": "Microsoft",
    "NET": "Cloudflare",
    "NOW": "ServiceNow",
    "NTNX": "Nutanix",
    "NVDA": "NVIDIA",
    "OKTA": "Okta",
    "PANW": "Palo Alto Networks",
    "PATH": "UiPath",
    "PAYC": "Paycom",
    "PCOR": "Procore",
    "PCTY": "Paylocity",
    "PLTR": "Palantir",
    "RBRK": "Rubrik",
    "SAIL": "SailPoint",
    "SHOP": "Shopify",
    "SNOW": "Snowflake",
    "TEAM": "Atlassian",
    "TOST": "Toast",
    "TTAN": "ServiceTitan",
    "TWLO": "Twilio",
    "VEEV": "Veeva Systems",
    "WDAY": "Workday",
    "ZS": "Zscaler",
}
